version: '3.7'

services:
  movie-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      telegram-bot-api:
        condition: service_healthy
    env_file:
      - .env

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
      TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
      TELEGRAM_LOCAL: "1"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api

volumes:
  telegram-bot-api-data: